/* FloodTwin Q1 Demo — core: namespace, state, event bus, i18n, utils */
(function () {
  "use strict";

  const FT = (window.FT = window.FT || {});

  /* ---------- event bus ---------- */
  const listeners = {};
  FT.bus = {
    on(evt, fn) { (listeners[evt] = listeners[evt] || []).push(fn); return fn; },
    off(evt, fn) { const a = listeners[evt]; if (a) { const i = a.indexOf(fn); if (i >= 0) a.splice(i, 1); } },
    emit(evt, payload) { (listeners[evt] || []).forEach((fn) => { try { fn(payload); } catch (e) { console.error(`[FT.bus:${evt}]`, e); } }); },
  };

  /* ---------- global state ---------- */
  FT.state = {
    lang: "vi",
    scenario: "oct2020",
    policy: "rule",            // "rule" | "mpc"
    workspace: "map",          // "map" | "city" | "plant"
    selectedFacilityId: "a-vuong",
    mpcApproved: false,
    timeH: -6,                 // simulation time, hours relative to "now" [-24, +48]
    playing: true,
    speed: 1800,               // sim-seconds per real-second (30 sim-min/s)
    view: "3d",               // "3d" | "2d"
    camPreset: "overview",
    selectedGauge: "aiNghia",
    rainScale: 1.0,
    ensSpread: 1.0,
    layers: { water: true, flow: true, traffic: true, roads: true, gauges: true, reservoirs: true, rain: true, labels: true, zones: true, shelters: true, bldg: true, impact: true },
    quality: "high",
    threeReady: null,          // null = pending, true/false
  };

  /* ---------- i18n ---------- */
  const STR = {
    vi: {
      "tagline": "Bản sao số lũ & liên hồ chứa · nhận thức bất định · nền tảng pháp quy",
      "kpi.alert": "Cảnh báo lưu vực", "kpi.rain": "Mưa lưu vực", "kpi.gauge": "Ái Nghĩa", "kpi.roads": "Mạng đường thông", "kpi.leadtime": "Lead time hiệu dụng",
      "scenario.label": "Kịch bản",
      "scenario.oct2020": "Lũ tháng 10/2020 (lịch sử)", "scenario.yagi": "Siêu bão kiểu Yagi (cực đoan)", "scenario.monsoon": "Gió mùa trung bình", "scenario.recovery": "Phục hồi sau đỉnh",
      "workspace.nav": "Không gian vận hành",
      "workspace.city": "Điều hành thành phố",
      "workspace.plant": "Vận hành nhà máy",
      "workspace.registryGap": "Khoảng trống sổ đăng ký",
      "workspace.decisionQueue": "Hàng chờ quyết định",
      "workspace.approvedOrder": "Lệnh đã phê duyệt",
      "workspace.checklist": "Danh sách kiểm tra",
      "workspace.notInDemo": "Không có trong bản demo hiện tại",
      "workspace.conflictingSources": "Nguồn mâu thuẫn",
      "city.eyebrow": "Điều hành thành phố",
      "city.title": "Bảng điều phối đô thị",
      "city.lead": "Độ phủ sổ đăng ký, quyết định chịu trách nhiệm, mô phỏng hạ lưu và bằng chứng sẵn sàng cho quy trình lũ dùng chung.",
      "city.synthetic": "Không gian mô phỏng tổng hợp · {total} công trình đô thị trong phạm vi nguồn · {time}",
      "city.scope": "Phạm vi đô thị",
      "city.registrySource": "nguồn sổ đăng ký Đà Nẵng",
      "city.named": "Công trình đã định danh",
      "city.authoritativeNames": "tên có thẩm quyền",
      "city.unresolved": "Danh tính chưa giải quyết",
      "city.notRowExpanded": "không mở rộng thành dòng",
      "city.portfolio": "Danh mục được quản trị",
      "city.portfolioLabel": "Danh mục thủy điện được quản trị",
      "city.processTimeline": "Dòng thời gian quy trình",
      "city.processTimelineLabel": "Dòng thời gian quy trình công trình",
      "city.decisionQueueLabel": "Hàng chờ quyết định",
      "city.downstreamImpact": "Tác động hạ lưu",
      "city.downstreamImpactLabel": "Tác động mô phỏng hạ lưu",
      "city.readiness": "Sẵn sàng",
      "city.readinessLabel": "Sẵn sàng thông báo và kiểm toán",
      "city.demoMapped": "Trạng thái thủy văn đã ánh xạ demo",
      "city.registryOnly": "Danh tính đô thị chỉ có trong sổ đăng ký",
      "city.plantRoute": "Tuyến nhà máy",
      "city.openPlant": "Mở không gian nhà máy cho {name}",
      "city.simPending": "Mô phỏng đang chờ",
      "city.noExecution": "Trạng thái quy trình dùng chung hoặc đường cơ sở demo đã đánh giá; không mở quyền điều khiển thực thi nhà máy.",
      "city.noExecutionOrder": "approved_order_id {id}; status {status}; không mở quyền điều khiển thực thi nhà máy.",
      "city.noPackage": "Chưa có gói quyết định xả đang hoạt động",
      "city.noPackageNote": "Nhãn vai trò chịu trách nhiệm chưa có cho đến khi tồn tại gói đề xuất.",
      "city.accountableRole": "Vai trò chịu trách nhiệm: {role}",
      "city.consulted": "Tham vấn: {roles}",
      "city.consultedNone": "Vai trò tham vấn: chưa ghi nhận",
      "city.approvalEvidence": "Bằng chứng phê duyệt chịu trách nhiệm được lưu trong vết kiểm toán.",
      "city.queueMeta": "{proposals} đề xuất · {orders} lệnh đã phê duyệt trong ảnh chụp quy trình xả dùng chung",
      "city.unresolvedText": "{count} danh tính đang chờ sổ đăng ký có thẩm quyền",
      "city.alertTrend": "Cảnh báo {alert} · xu thế {trend} m/3h",
      "city.simUnavailable": "Không có mô phỏng",
      "city.simProvenance": "Nguồn gốc mô phỏng: FT.hydro.at(FT.state.timeH), dữ liệu demo tổng hợp; không phải telemetry quan trắc thời gian thực.",
      "city.auditEntries": "Mục kiểm toán",
      "city.auditNote": "nhật ký cục bộ chỉ ghi thêm",
      "city.notificationEvidence": "Bằng chứng thông báo",
      "city.notificationNote": "không giả định đã gửi",
      "city.workflowEvidence": "Bằng chứng quy trình",
      "city.workflowNote": "vết quyết định/xả",
      "city.noRefusal": "Chưa ghi nhận từ chối phê duyệt cho sự kiện hiện tại.",
      "city.refusal": "Phê duyệt bị từ chối gần nhất: {actor} thiếu {role}; không tạo lệnh đã phê duyệt.",
      "city.readinessProvenance": "Nguồn/sổ kiểm toán sẵn sàng: FT.ops.audit.entries. Số 0 nghĩa là chưa có bằng chứng ghi trong phiên trình duyệt này.",
      "city.unknownRole": "vai trò không xác định",
      "city.requiredRole": "vai trò bắt buộc",
      "city.unassignedRaci": "chưa phân công trong RACI",
      "plant.eyebrow": "Vận hành nhà máy",
      "plant.unknownFacility": "Công trình không xác định",
      "plant.lead": "Trạng thái hồ, vòng đời khuyến nghị, ranh giới phê duyệt và mức sẵn sàng thực thi cho công trình được quản trị đã chọn.",
      "plant.synthetic": "Không gian vận hành tổng hợp · dữ liệu có nhãn nguồn · {time}",
      "plant.noRegistry": "Không có bản ghi sổ đăng ký được quản trị",
      "plant.facility": "Công trình",
      "plant.facilityAria": "Công trình nhà máy",
      "plant.registrySource": "Nguồn gốc/sổ đăng ký: {source}; ngày nguồn {date}; trạng thái vận hành {state}.",
      "plant.registryMissing": "Nguồn gốc/sổ đăng ký: lựa chọn không có trong sổ đăng ký được quản trị.",
      "plant.currentState": "Trạng thái hiện tại",
      "plant.currentStateLabel": "Trạng thái nhà máy hiện tại",
      "plant.noPlantData": "{name} là danh tính {type} được quản trị, nhưng dữ liệu vận hành nhà máy là NOT_IN_CURRENT_DEMO.",
      "plant.selectedUnavailable": "Công trình được chọn không có trong sổ đăng ký được quản trị.",
      "plant.inspectionSource": "Trạng thái kiểm tra: {status}; bằng chứng/nguồn {source}; ngày {date}.",
      "plant.noSource": "Không có bản ghi nguồn cho lựa chọn này.",
      "plant.reservoirLevel": "Mực hồ",
      "plant.inflow": "Dòng vào",
      "plant.currentRelease": "Lưu lượng xả hiện tại",
      "plant.freeboard": "Freeboard",
      "plant.syntheticReservoir": "trạng thái hồ tổng hợp",
      "plant.simNotTelemetry": "mô phỏng, không phải telemetry",
      "plant.simActivePolicy": "chính sách đang hoạt động mô phỏng",
      "plant.assumedDesign": "giá trị thiết kế giả định",
      "plant.marginUnavailable": "không có biên an toàn",
      "plant.marginFailed": "{state}: không tính được biên an toàn cho {name}; không thay thế bằng freeboard hoặc biên số.",
      "plant.stateProvenance": "Nguồn gốc trạng thái: FT.hydro.at(FT.state.timeH), mô hình hồ tổng hợp hydro.js; ngày nguồn {date}; giá trị là mô phỏng/giả định, không phải quan trắc.",
      "plant.advisory": "Khuyến nghị tư vấn",
      "plant.advisoryLabel": "Khuyến nghị tư vấn",
      "plant.noAdvisory": "NOT_IN_CURRENT_DEMO: không tính khuyến nghị nhà máy, đề xuất xả, chỉ dẫn cửa van, chỉ số so sánh xả hay hướng dẫn vận hành cho công trình này.",
      "plant.lifecycle": "Lớp vòng đời: {class}; có thể hành động: {actionable}",
      "plant.notTargeted": "{name} hiện không được gói đề xuất nhắm tới. Không hiển thị khuyến nghị xả, chỉ dẫn cửa van, hiệu lực đề xuất hay phương án gói cho công trình này.",
      "plant.proposeUnavailable": "Không thể đề xuất kế hoạch",
      "plant.approveUnavailable": "Không thể phê duyệt",
      "plant.executeUnavailable": "Không thể thực thi",
      "plant.proposeReason": "Task 7 nối sự kiện đề xuất; Task 6 giữ khuyến nghị không thể hành động.",
      "plant.approveReason": "Chỉ phê duyệt có định danh và đúng thẩm quyền mới tạo được lệnh đã phê duyệt.",
      "plant.executeReason": "Không có lệnh đã phê duyệt hiện hành cho renderer này.",
      "plant.noActionable": "Không có khuyến nghị có thể hành động.",
      "plant.noProposal": "Không có gói đề xuất tại thời điểm hiện tại.",
      "plant.noProposalClass": "Không có gói quyết định loại đề xuất tại thời điểm hiện tại.",
      "plant.proposedRelease": "Lưu lượng xả đề xuất",
      "plant.start": "Bắt đầu",
      "plant.requiresApproval": "cần phê duyệt",
      "plant.controlPoint": "Điểm kiểm soát",
      "plant.downstreamSimulation": "mô phỏng hạ lưu",
      "plant.peakCut": "Giảm đỉnh",
      "plant.modelledComparison": "so sánh mô hình",
      "plant.gateAssumption": "ASSUMED_FOR_DEMO: ghi chú cửa van của gói cho {name}: {gates}. Hình học từng cửa van không được mô hình hóa; không có độ mở cửa đã xác minh.",
      "plant.advisorySource": "Nguồn gốc khuyến nghị: FT.ops.package và FT.lifecycle; đề xuất snapshot cho công trình này: {proposal}.",
      "plant.advisoryHiddenSource": "Nguồn gốc khuyến nghị: chỉ có sổ đăng ký và trạng thái thủy văn của {name}; đầu ra khuyến nghị bị ẩn trừ khi công trình được chọn là mục tiêu gói.",
      "plant.alternatives": "Phương án thay thế",
      "plant.noNumericNotDemo": "Không tính phương án số cho công trình NOT_IN_CURRENT_DEMO.",
      "plant.noNumericNotTarget": "Không hiển thị phương án số cho {name} vì hiện không được gói đề xuất nhắm tới.",
      "plant.noAlternatives": "Không có phương án so sánh tại thời điểm hiện tại.",
      "plant.modelledPeak": "Đỉnh mô hình {peak} m",
      "plant.modelledPeakUnavailable": "Không có đỉnh mô hình",
      "plant.noNote": "Không có ghi chú.",
      "plant.approvedOrderLabel": "Lệnh đã phê duyệt",
      "plant.noApprovedOrder": "Không có lệnh vận hành đã phê duyệt/hiện hành cho công trình này.",
      "plant.recommendationBoundary": "Khuyến nghị tách biệt với lệnh đã phê duyệt. Renderer này không tạo lệnh vận hành.",
      "plant.approvedOrderId": "ID lệnh đã phê duyệt",
      "plant.package": "Gói",
      "plant.commandedTarget": "Mục tiêu đã lệnh",
      "plant.decisionAudit": "Kiểm toán quyết định",
      "plant.checklistLabel": "Danh sách kiểm tra vận hành",
      "plant.checklistLocked": "Danh sách kiểm tra khóa cho đến khi có lệnh đã phê duyệt.",
      "plant.execution": "Thực thi",
      "plant.executionLabel": "Trạng thái thực thi",
      "plant.noExecutionState": "Không có trạng thái thực thi. Điều khiển thực thi không khả dụng cho đến khi phê duyệt.",
      "plant.order": "Lệnh",
      "plant.commandedRelease": "Lưu lượng xả đã lệnh",
      "plant.observedRelease": "Lưu lượng xả quan trắc",
      "plant.deviation": "Sai lệch",
      "plant.notStarted": "chưa bắt đầu",
      "plant.approvedCommand": "lệnh đã phê duyệt",
      "plant.telemetryMissing": "không có telemetry",
      "plant.tolerance": "Dung sai thực tế-so-với-lệnh: {value} m3/s giả định demo; không phải ngưỡng pháp quy.",
      "plant.startExecution": "Bắt đầu thực thi",
      "plant.startReason": "Cần khớp order-valid, notifications-acknowledged, plant-ready và outlet-ready.",
      "plant.recordActual": "Ghi thực tế mô phỏng",
      "plant.recordReason": "Ghi lưu lượng xả hồ của công trình đã chọn từ mô hình tổng hợp.",
      "plant.closeComplete": "Đóng hoàn tất",
      "plant.closeReason": "Cần quan trắc thực thi và các kiểm tra hoàn tất.",
      "plant.missingDependencies": "Phụ thuộc vận hành còn thiếu",
      "plant.identityMeta": "{id} · {type} · kiểm tra {status}",
      "plant.check.order-valid": "ID lệnh, sự kiện và công trình khớp với demo hiện tại",
      "plant.check.notifications-acknowledged": "Thông báo hạ du đã được xác nhận",
      "plant.check.plant-ready": "Kíp nhà máy sẵn sàng",
      "plant.check.outlet-ready": "Tuyến xả sẵn sàng",
      "plant.check.ramp-started": "Đã bắt đầu tăng xả",
      "plant.check.actual-recorded": "Đã ghi lưu lượng xả thực tế",
      "plant.check.downstream-monitored": "Đã theo dõi phản ứng hạ du",
      "plant.check.completion-confirmed": "Đã xác nhận hoàn tất",
      "plant.recommendationOnly": "chỉ là RECOMMENDATION",
      "plant.revision": "phiên bản {revision}",
      "plant.assumedCommand": "lệnh ASSUMED_FOR_DEMO từ gói đã phê duyệt",
      "plant.storedApproval": "bằng chứng phê duyệt đã lưu",
      "plant.noneStored": "chưa lưu",
      "plant.dep.telemetry": "chưa cấp nguồn telemetry cho bản demo này",
      "plant.dep.storage": "chưa cấp dung tích/hình học cửa xả cho bản demo này",
      "plant.dep.rules": "chưa cấp quy tắc vận hành nhà máy cho bản demo này",
      "plant.dep.routing": "chưa cấp đầu vào định tuyến/dự báo cho công trình này",
      "city.accountableApproval": "Phê duyệt chịu trách nhiệm: {actor}; lý do: {reason}",
      "policy.rule": "Rule curve tĩnh", "policy.mpc": "FloodTwin MPC",
      "panel.forcing": "Cưỡng bức khí tượng", "ctl.rainScale": "Hệ số mưa (× ensemble)", "ctl.ensSpread": "Độ mở ensemble",
      "ctl.note": "Chuỗi GraphCast/GenCast + IMERG hiệu chỉnh — dữ liệu tổng hợp minh hoạ.",
      "panel.layers": "Lớp hiển thị",
      "layer.water": "Mặt nước / ngập", "layer.flow": "Hạt dòng chảy", "layer.traffic": "Giao thông", "layer.roads": "Trạng thái đường",
      "layer.gauges": "Trạm thủy văn", "layer.reservoirs": "Hồ chứa / đập", "layer.rain": "Mưa", "layer.labels": "Nhãn địa danh",
      "panel.legend": "Chú giải", "legend.depth": "Độ sâu ngập (m)", "legend.road": "Khả năng lưu thông", "legend.alert": "Mức báo động trạm",
      "road.open": "Thông suốt", "road.caution": "Chú ý (<15 cm)", "road.risk": "Hạn chế (15–30 cm)", "road.closed": "Đóng (≥30 cm)",
      "alert.normal": "Bình thường",
      "panel.metrics": "Ngưỡng đạt mục tiêu · đề cương §8", "metrics.synthetic": "demo tổng hợp",
      "metrics.note": "Đây là ngưỡng đặt ra, chưa phải số đo. Độ chính xác chỉ chứng minh được bằng đối chứng lùi trên trận lũ thật.",
      "metrics.extent": "(diện ngập)", "metrics.pending": "· chưa đo", "metrics.selftest": "Tự kiểm định vật lý", "metrics.measured": "· đã đo mỗi lần khởi động",
      "metrics.dem": "Độ phân giải DEM", "metrics.mass": "Bảo toàn khối (SWE)", "metrics.measured2": "· đo thật",
      "metrics.surrogate": "Surrogate FNO/DeepONet", "metrics.planned": "kế hoạch — chưa huấn luyện", "forcing.src": "Kịch bản tổng hợp",
      "view.3d": "Song sinh số 3D", "view.2d": "Bản đồ vận hành 2D",
      "cam.overview": "Toàn cảnh", "cam.delta": "Hạ lưu", "cam.dams": "Bậc thang hồ", "cam.hoian": "Hội An",
      "hint.orbit": "Kéo xoay · lăn thu phóng · phải rê dịch", "hint.pan2d": "Kéo dịch chuyển · lăn thu phóng · nhấp trạm/hồ để xem",
      "explain.mapHelp": "Dùng phím mũi tên để di chuyển con trỏ kiểm tra, Enter để chọn, Escape để đóng.",
      "explain.eyebrow": "Trạng thái vật lý đã chuẩn hóa", "explain.title": "Giải thích trạng thái này", "explain.close": "Đóng giải thích",
      "explain.quantities": "Đại lượng", "explain.sources": "Nguồn và xuất xứ", "explain.confidence": "Bất định và độ tin cậy",
      "explain.assumptions": "Giả định", "explain.limitations": "Giới hạn", "explain.docs": "Đọc kiến trúc khoa học",
      "explain.degradation": "Bằng chứng suy giảm", "explain.missingQuantity": "Đại lượng bị thiếu", "explain.missingDependency": "Phụ thuộc bị thiếu",
      "explain.lastValid": "Thời điểm hợp lệ gần nhất", "explain.confidenceEffect": "Ảnh hưởng đến độ tin cậy", "explain.permittedUse": "Phạm vi được phép dùng",
      "explain.status": "Trạng thái", "explain.valid": "Thời điểm hiệu lực", "explain.issue": "Thời điểm phát hành", "explain.notComputed": "chưa được tính",
      "explain.age": "Tuổi dữ liệu", "explain.quality": "Chất lượng", "explain.flags": "Cờ chất lượng", "explain.reason": "Lý do",
      "explain.grade": "Mức tin cậy", "explain.uncertaintyDetail": "Bất định", "explain.unavailable": "không có",
      "explain.methodGateway": "Giải thích trạng thái này", "explain.selection.point": "Ô lưới", "explain.selection.feature": "Đối tượng",
      "explain.label.gauge": "Giải thích trạm", "explain.label.reservoir": "Giải thích hồ chứa",
      "badge.flooded": "Diện ngập", "badge.people": "Dân cư phơi nhiễm",
      "fallback.webgl": "Không tải được WebGL/Three.js — chuyển sang bản đồ 2D (đầy đủ mô phỏng).",
      "tl.observed": "quan trắc", "tl.now": "HIỆN TẠI", "tl.forecast": "dự báo ensemble",
      "panel.gauge": "Trạm thủy văn · dự báo xác suất",
      "gauge.stage": "Mực nước", "gauge.trend": "Xu thế 3h", "gauge.alert": "Báo động",
      "chart.obs": "Quan trắc", "chart.median": "Trung vị",
      "panel.reservoir": "Bậc thang liên hồ · QĐ 1865/QĐ-TTg",
      "mpc.title": "Đề xuất xả trước (MPC · nằm trong hành lang pháp lý)",
      "mpc.approve": "Phê duyệt", "mpc.details": "Gói quyết định", "mpc.reject": "Từ chối",
      "mpc.note": "Không cửa van nào vận hành theo lời LLM — người trực phê duyệt mọi lệnh xả.",
      "mpc.approved": "ĐÃ PHÊ DUYỆT", "mpc.applied": "Đang xả trước theo lệnh đã phê duyệt",
      "panel.traffic": "Giao thông mô phỏng · cập nhật liên tục",
      "tr.open": "Mạng thông", "tr.closed": "Đoạn đóng", "tr.reroute": "Xe đổi lộ trình", "tr.eta": "ETA ĐN→Hội An",
      "tr.veh": "xe", "tr.blocked": "tắc",
      "panel.llm": "Lớp LLM có kiểm soát · RAG", "llm.grounded": "100% trích nguồn",
      "llm.placeholder": "Nhấn tạo bản tin để tổng hợp tình huống — mọi con số lấy từ solver/optimizer, mọi mệnh đề kèm trích dẫn.",
      "llm.generate": "Tạo bản tin tình huống", "llm.citizen": "Hỏi đáp cư dân Hội An",
      "panel.log": "Nhật ký sự kiện",
      "panel.zones": "Khu vực giám sát", "kpi.zones": "KV nguy cơ/khẩn cấp",
      "layer.zones": "Vòng khu vực", "layer.bldg": "Tòa nhà", "layer.impact": "Tác động dân cư",
      "impact.homes": "Nhà ngập",
      "legend.impact": "Tác động dân cư", "legend.heat": "Nhiệt đồ dân × ngập", "legend.h15": "Nhà ngập ≥15 cm", "legend.h50": "Nhà ngập ≥50 cm",
      "zone.depth": "Ngập max", "zone.mean": "Ngập TB", "zone.exposed": "Phơi nhiễm", "zone.access": "Tiếp cận EOC",
      "zone.accessOk": "thông", "zone.accessCut": "MẤT TUYẾN", "zone.pois": "Hạ tầng trọng yếu", "zone.actions": "Khuyến nghị hành động",
      "zone.flyto": "Đến vị trí", "zone.history": "Diễn biến ngập (T−24h→nay)", "zone.gauge": "Trạm gần nhất",
      "zone.st0": "An toàn", "zone.st1": "Theo dõi", "zone.st2": "Nguy cơ", "zone.st3": "KHẨN CẤP",
      "zone.toRed": "chuyển mức KHẨN CẤP", "zone.toOrange": "chuyển mức nguy cơ", "zone.improved": "hạ mức — tình hình cải thiện",
      "zone.ok": "OK", "zone.flooded": "ngập", "modal.zone": "Chi tiết khu vực",
      "foot.mode": "Dữ liệu tổng hợp minh hoạ phương pháp — không dùng cho vận hành thật", "foot.docs": "Tài liệu kỹ thuật", "hint.mobile": "Đang xem trên màn hình nhỏ. Bản đồ vận hành 2D được ưu tiên; xoay ngang máy hoặc mở trên máy tính để thấy đủ bảng hồ chứa, dự báo và khu vực giám sát.",
      "alert.bd": "BĐ", "alert.over": "Trên BĐ3",
      "phase.calm": "Ổn định", "phase.watch": "Theo dõi", "phase.rise": "Nước lên", "phase.peak": "Đỉnh lũ", "phase.recede": "Nước rút",
      "unit.people": "người", "unit.min": "ph",
      "res.inflow": "vào", "res.outflow": "xả", "res.ceil": "trần trước lũ", "res.gate": "cửa van", "res.preRelease": "xả trước",
      "modal.decision": "Gói quyết định · xả trước MPC", "modal.brief": "Bản tin tình huống (LLM có kiểm soát)", "modal.citizen": "Hỏi đáp cư dân — Hội An",
      "dp.proposed": "Lệnh xả đề xuất", "dp.envelope": "Bao dòng vào ensemble", "dp.legal": "Điều khoản pháp lý", "dp.residual": "Rủi ro tồn dư", "dp.downstream": "Hạ lưu dự kiến",
      "toast.mpcOn": "Đã kích hoạt tối ưu MPC — đề xuất xả trước sẵn sàng chờ phê duyệt.",
      "toast.approved": "Lệnh xả trước đã được phê duyệt — cập nhật dự báo hạ lưu.",
      "toast.rejected": "Đã từ chối đề xuất. Giữ vận hành theo rule curve.",
      "toast.scenario": "Đã nạp kịch bản", "toast.reroute": "Giao thông tự động định tuyến lại quanh đoạn ngập",
      "tour.btn": "Trình diễn",
      "tour.s1": "🎬 Trình diễn — Lũ 10/2020: theo dõi nước lên từ thượng nguồn", "tour.s2": "Vùng trũng ven sông ngập trước — xe bắt đầu đổi lộ trình",
      "tour.s3": "Đỉnh lũ theo RULE CURVE: Ái Nghĩa vượt BĐ3, nhiều tuyến đường đóng", "tour.s4": "FloodTwin MPC nhìn thấy trước đỉnh lũ — đề xuất xả trước chờ phê duyệt",
      "tour.s5": "Người trực PHÊ DUYỆT — hồ hạ mực nước đón lũ", "tour.s6": "Cùng đỉnh lũ với MPC: mực hạ lưu giảm rõ — so sánh 2 đường trên biểu đồ",
      "tour.end": "🎬 Kết thúc trình diễn — mời bạn tự do khám phá", "tour.cancel": "Đã dừng trình diễn",
      "report.btn": "Xuất báo cáo", "report.title": "BÁO CÁO TÌNH HUỐNG LŨ — LƯU VỰC VU GIA – THU BỒN",
      "report.at": "Thời điểm", "report.gauges": "Trạm thủy văn", "report.res": "Hồ chứa", "report.zones": "Khu vực trọng điểm", "report.traffic": "Giao thông",
      "report.stage": "Mực nước (m)", "report.alert": "Báo động", "report.level": "Mực hồ (m)", "report.ceil": "Trần trước lũ", "report.io": "Vào / Xả (m³/s)",
      "report.depth": "Ngập max (m)", "report.exposed": "Phơi nhiễm", "report.access": "Tiếp cận EOC", "report.brief": "Tóm tắt tình huống",
      "modal.method": "Phương pháp — cái gì thật, cái gì tổng hợp",
      "rec.btn": "Hồ sơ quyết định", "modal.record": "Hồ sơ quyết định · sổ ghi",
      "rec.none": "Chưa có quyết định nào được ghi. Phê duyệt hoặc từ chối một đề xuất, hồ sơ sẽ được niêm phong ngay tại thời điểm bấm.",
      "rec.print": "In · xuất PDF", "rec.json": "Tải JSON", "rec.apxOpt": "Kèm phụ lục",
      "rec.superseded": "Bối cảnh thay đổi — một quyết định đang mở đã được ghi là bị thay thế",
      "rec.title": "HỒ SƠ QUYẾT ĐỊNH VẬN HÀNH LIÊN HỒ",
      "rec.wm": "DEMO · CHƯA KÝ",
      "rec.banner": "Hồ sơ sinh từ bản trình diễn công khai với dữ liệu tổng hợp. Không phải hồ sơ của một lần vận hành thật, không có chữ ký, không dùng để đối chiếu trách nhiệm.",
      "rec.what": "Quyết định là gì", "rec.when": "Vào lúc nào", "rec.expect": "Dự kiến xảy ra điều gì",
      "rec.clause": "Điều khoản cho phép", "rec.risk": "Điều gì vẫn có thể xảy ra",
      "rec.who": "Ai quyết định", "rec.check": "Kiểm chứng lại bằng cách nào",
      "rec.roleDemo": "vai chưa xác lập, bản demo không có tài khoản",
      "rec.foot": "FloodTwin · SkyLabs — hồ sơ demo, chưa ký. Dấu băm kiểm lại được mà không cần liên hệ chúng tôi.",
      "rec.apx": "PHỤ LỤC HỒ SƠ QUYẾT ĐỊNH", "rec.apxSeq": "Trình tự quyết định",
      "rec.apxGauge": "Trạm thủy văn tại thời điểm niêm phong", "rec.apxRes": "Hồ chứa tại thời điểm niêm phong",
      "rec.apxForcing": "Cưỡng bức và kịch bản", "rec.apxProv": "Nguồn gốc dữ liệu",
      "rec.out.approved": "ĐÃ PHÊ DUYỆT", "rec.out.rejected": "ĐÃ TỪ CHỐI", "rec.out.superseded": "BỊ THAY THẾ",
      "rec.sealed": "Đã niêm phong hồ sơ quyết định",
      "rec.apxBand": "Bao ensemble tại đỉnh",
      "rec.bandSrc": "Phân vị ensemble của bộ diễn toán trong trình duyệt, đọc tại thời điểm trung vị đạt đỉnh",
      "rec.clk.client_clock_unsynchronised": "đồng hồ máy người dùng, không đồng bộ",
      "rec.src.terrain_real": "Địa hình thật (AWS Terrain Tiles)",
      "rec.src.legal_real": "Văn bản pháp lý thật (QĐ 1865/QĐ-TTg)",
      "rec.src.forcing_synthetic": "Cưỡng bức giải tích (tổng hợp)",
      "rec.src.solver_local": "Bộ giải nước nông chạy ngay trong trình duyệt này",
      "log.start": "Khởi tạo bản sao số VGTB — 4 hồ chứa, 2 trạm chính, lưới SWE 288².",
      "ev.bd1": "vượt báo động 1", "ev.bd2": "vượt báo động 2", "ev.bd3": "vượt BÁO ĐỘNG 3", "ev.below": "xuống dưới báo động 1",
      "ev.roadClosed": "ngập ≥30 cm — đóng đường", "ev.roadOpen": "nước rút — mở lại",
      "ev.gateOpen": "tăng cửa xả", "ev.peak": "qua đỉnh lũ tại", "ev.rainPeak": "đỉnh mưa lưu vực",
    },
    en: {
      "tagline": "Flood & inter-reservoir digital twin · uncertainty-aware · regulation-grounded",
      "kpi.alert": "Basin alert", "kpi.rain": "Basin rainfall", "kpi.gauge": "Ai Nghia", "kpi.roads": "Road network open", "kpi.leadtime": "Effective lead time",
      "scenario.label": "Scenario",
      "scenario.oct2020": "Oct 2020 flood (historical)", "scenario.yagi": "Yagi-class typhoon (extreme)", "scenario.monsoon": "Average monsoon", "scenario.recovery": "Post-peak recovery",
      "workspace.nav": "Operations workspaces",
      "workspace.city": "City operations",
      "workspace.plant": "Plant operations",
      "workspace.registryGap": "Registry gap",
      "workspace.decisionQueue": "Decision queue",
      "workspace.approvedOrder": "Approved order",
      "workspace.checklist": "Checklist",
      "workspace.notInDemo": "Not in current demo",
      "workspace.conflictingSources": "Conflicting sources",
      "city.eyebrow": "City operations",
      "city.title": "Municipal coordination dashboard",
      "city.lead": "Registry coverage, accountable decisions, downstream simulation and readiness evidence for the shared flood workflow.",
      "city.synthetic": "Synthetic simulation workspace · {total} municipal facilities in source scope · {time}",
      "city.scope": "Municipal scope",
      "city.registrySource": "DN registry source",
      "city.named": "Named facilities",
      "city.authoritativeNames": "authoritative names",
      "city.unresolved": "Unresolved identities",
      "city.notRowExpanded": "not row-expanded",
      "city.portfolio": "Governed portfolio",
      "city.portfolioLabel": "Governed hydropower portfolio",
      "city.processTimeline": "Process timeline",
      "city.processTimelineLabel": "Facility process timeline",
      "city.decisionQueueLabel": "Decision queue",
      "city.downstreamImpact": "Downstream impact",
      "city.downstreamImpactLabel": "Downstream simulation impact",
      "city.readiness": "Readiness",
      "city.readinessLabel": "Notification and audit readiness",
      "city.demoMapped": "Demo-mapped hydro state",
      "city.registryOnly": "Registry-only municipal identity",
      "city.plantRoute": "Plant route",
      "city.openPlant": "Open plant workspace for {name}",
      "city.simPending": "Simulation pending",
      "city.noExecution": "Shared workflow state or assessed demo baseline; no plant execution control exposed.",
      "city.noExecutionOrder": "approved_order_id {id}; status {status}; no plant execution control exposed.",
      "city.noPackage": "No active release decision package",
      "city.noPackageNote": "Accountable role label unavailable until a proposal-class package exists.",
      "city.accountableRole": "Accountable role: {role}",
      "city.consulted": "Consulted: {roles}",
      "city.consultedNone": "Consulted roles: none recorded",
      "city.approvalEvidence": "Accountable approval evidence stored in audit trail.",
      "city.queueMeta": "{proposals} proposals · {orders} approved orders in shared release workflow snapshot",
      "city.unresolvedText": "{count} identities awaiting authoritative registry",
      "city.alertTrend": "Alert {alert} · trend {trend} m/3h",
      "city.simUnavailable": "Simulation unavailable",
      "city.simProvenance": "Simulation provenance: FT.hydro.at(FT.state.timeH), synthetic demo data; not observed real-time telemetry.",
      "city.auditEntries": "Audit entries",
      "city.auditNote": "append-only local log",
      "city.notificationEvidence": "Notification evidence",
      "city.notificationNote": "dispatch not assumed",
      "city.workflowEvidence": "Workflow evidence",
      "city.workflowNote": "release/decision trail",
      "city.noRefusal": "No refused approval recorded for the current event.",
      "city.refusal": "Latest refused approval: {actor} lacked {role}; no approved order created.",
      "city.readinessProvenance": "Readiness source/provenance: FT.ops.audit.entries. Zero means no recorded evidence in this browser session.",
      "city.unknownRole": "unknown role",
      "city.requiredRole": "required role",
      "city.unassignedRaci": "unassigned in RACI",
      "plant.eyebrow": "Plant operations",
      "plant.unknownFacility": "Unknown facility",
      "plant.lead": "Reservoir state, recommendation lifecycle, approval boundary and execution readiness for the selected governed facility.",
      "plant.synthetic": "Synthetic operations workspace · source-labelled data · {time}",
      "plant.noRegistry": "No governed registry match",
      "plant.facility": "Facility",
      "plant.facilityAria": "Plant facility",
      "plant.registrySource": "Registry provenance/source: {source}; source date {date}; operational state {state}.",
      "plant.registryMissing": "Registry provenance/source: selected facility is not available in the governed registry.",
      "plant.currentState": "Current state",
      "plant.currentStateLabel": "Current plant state",
      "plant.noPlantData": "{name} is a governed {type} identity, but operational plant data are NOT_IN_CURRENT_DEMO.",
      "plant.selectedUnavailable": "Selected facility is not available in the governed registry.",
      "plant.inspectionSource": "Inspection status: {status}; evidence/source {source}; date {date}.",
      "plant.noSource": "No source record available for this selection.",
      "plant.reservoirLevel": "Reservoir level",
      "plant.inflow": "Inflow",
      "plant.currentRelease": "Current release",
      "plant.freeboard": "Freeboard",
      "plant.syntheticReservoir": "synthetic reservoir state",
      "plant.simNotTelemetry": "simulated, not telemetry",
      "plant.simActivePolicy": "simulated active policy",
      "plant.assumedDesign": "assumed design values",
      "plant.marginUnavailable": "safety margin unavailable",
      "plant.marginFailed": "{state}: safety margin could not be calculated for {name}; no numeric freeboard or margin value is substituted.",
      "plant.stateProvenance": "State provenance: FT.hydro.at(FT.state.timeH), hydro.js synthetic reservoir model; source date {date}; values are simulated/assumed, not observations.",
      "plant.advisory": "Advisory recommendation",
      "plant.advisoryLabel": "Advisory recommendation",
      "plant.noAdvisory": "NOT_IN_CURRENT_DEMO: no plant advisory, release recommendation, gate instruction, release-comparison metric or operational guidance is computed for this facility.",
      "plant.lifecycle": "Lifecycle class: {class}; actionable: {actionable}",
      "plant.notTargeted": "{name} is not currently targeted by a proposal-class package. No release recommendation, gate instruction, proposal validity or package alternative is rendered for this facility.",
      "plant.proposeUnavailable": "Propose plan unavailable",
      "plant.approveUnavailable": "Approve unavailable",
      "plant.executeUnavailable": "Execute unavailable",
      "plant.proposeReason": "Task 7 wires proposal events; Task 6 keeps recommendations non-actionable.",
      "plant.approveReason": "Only an attributed entitled approval can create an approved order.",
      "plant.executeReason": "No approved order is current for this renderer.",
      "plant.noActionable": "No actionable advisory is available.",
      "plant.noProposal": "No proposal-class package is available at the current time.",
      "plant.noProposalClass": "No current proposal-class decision package.",
      "plant.proposedRelease": "Proposed release",
      "plant.start": "Start",
      "plant.requiresApproval": "requires approval",
      "plant.controlPoint": "Control point",
      "plant.downstreamSimulation": "downstream simulation",
      "plant.peakCut": "Peak cut",
      "plant.modelledComparison": "modelled comparison",
      "plant.gateAssumption": "ASSUMED_FOR_DEMO: package gate note for {name}: {gates}. Individual gate geometry is not modelled; no verified gate openings are available.",
      "plant.advisorySource": "Advisory source/provenance: FT.ops.package and FT.lifecycle; snapshot proposal for this facility: {proposal}.",
      "plant.advisoryHiddenSource": "Advisory source/provenance: {name} registry and hydro state only; recommendation outputs are hidden unless the selected facility is the package target.",
      "plant.alternatives": "Alternatives",
      "plant.noNumericNotDemo": "No numeric alternatives are computed for NOT_IN_CURRENT_DEMO facilities.",
      "plant.noNumericNotTarget": "No numeric alternatives are rendered for {name} because it is not currently targeted by the proposal package.",
      "plant.noAlternatives": "No comparable alternatives are available at the current time.",
      "plant.modelledPeak": "Modelled peak {peak} m",
      "plant.modelledPeakUnavailable": "Modelled peak unavailable",
      "plant.noNote": "No note available.",
      "plant.approvedOrderLabel": "Approved order",
      "plant.noApprovedOrder": "No approved/current operational order for this facility.",
      "plant.recommendationBoundary": "Recommendations remain separate from approved orders. This renderer does not create operational orders.",
      "plant.approvedOrderId": "Approved order ID",
      "plant.package": "Package",
      "plant.commandedTarget": "Commanded target",
      "plant.decisionAudit": "Decision audit",
      "plant.checklistLabel": "Operational checklist",
      "plant.checklistLocked": "Checklist locked until an approved order exists.",
      "plant.execution": "Execution",
      "plant.executionLabel": "Execution status",
      "plant.noExecutionState": "No execution state. Execution controls remain unavailable until approval.",
      "plant.order": "Order",
      "plant.commandedRelease": "Commanded release",
      "plant.observedRelease": "Observed release",
      "plant.deviation": "Deviation",
      "plant.notStarted": "not started",
      "plant.approvedCommand": "approved command",
      "plant.telemetryMissing": "telemetry not supplied",
      "plant.tolerance": "Actual-versus-commanded tolerance: {value} m3/s demo assumption; not a regulatory threshold.",
      "plant.startExecution": "Start execution",
      "plant.startReason": "Requires order-valid, notifications-acknowledged, plant-ready and outlet-ready.",
      "plant.recordActual": "Record simulated actual",
      "plant.recordReason": "Records selected facility reservoir release from the synthetic model.",
      "plant.closeComplete": "Close complete",
      "plant.closeReason": "Requires execution observation and completion checks.",
      "plant.missingDependencies": "Missing operational dependencies",
      "plant.identityMeta": "{id} · {type} · inspection {status}",
      "plant.check.order-valid": "Order ID, event and facility match current demo",
      "plant.check.notifications-acknowledged": "Downstream notifications acknowledged",
      "plant.check.plant-ready": "Plant crew ready",
      "plant.check.outlet-ready": "Outlet path ready",
      "plant.check.ramp-started": "Ramp started",
      "plant.check.actual-recorded": "Actual release recorded",
      "plant.check.downstream-monitored": "Downstream response monitored",
      "plant.check.completion-confirmed": "Completion confirmed",
      "plant.recommendationOnly": "RECOMMENDATION only",
      "plant.revision": "revision {revision}",
      "plant.assumedCommand": "ASSUMED_FOR_DEMO command from approved package",
      "plant.storedApproval": "stored approval evidence",
      "plant.noneStored": "none stored",
      "plant.dep.telemetry": "telemetry feed not supplied to this demo",
      "plant.dep.storage": "storage/outlet geometry not supplied to this demo",
      "plant.dep.rules": "plant operating rules not supplied to this demo",
      "plant.dep.routing": "routing/forecast inputs not supplied for this facility",
      "city.accountableApproval": "Accountable approval: {actor}; reason: {reason}",
      "policy.rule": "Static rule curve", "policy.mpc": "FloodTwin MPC",
      "panel.forcing": "Meteorological forcing", "ctl.rainScale": "Rain factor (× ensemble)", "ctl.ensSpread": "Ensemble spread",
      "ctl.note": "GraphCast/GenCast chain + bias-corrected IMERG — synthetic demo data.",
      "panel.layers": "Layers",
      "layer.water": "Water / inundation", "layer.flow": "Flow particles", "layer.traffic": "Traffic", "layer.roads": "Road status",
      "layer.gauges": "River gauges", "layer.reservoirs": "Reservoirs / dams", "layer.rain": "Rainfall", "layer.labels": "Place labels",
      "panel.legend": "Legend", "legend.depth": "Flood depth (m)", "legend.road": "Passability", "legend.alert": "Gauge alert level",
      "road.open": "Open", "road.caution": "Caution (<15 cm)", "road.risk": "Restricted (15–30 cm)", "road.closed": "Closed (≥30 cm)",
      "alert.normal": "Normal",
      "panel.metrics": "Target thresholds · proposal §8", "metrics.synthetic": "synthetic demo",
      "metrics.note": "These are the thresholds we set, not measurements. Accuracy can only be shown by hindcasting a real flood.",
      "metrics.extent": "(flood extent)", "metrics.pending": "· not yet measured", "metrics.selftest": "Physics self-test", "metrics.measured": "· measured on every boot",
      "metrics.dem": "DEM resolution", "metrics.mass": "Mass conservation (SWE)", "metrics.measured2": "· measured",
      "metrics.surrogate": "FNO/DeepONet surrogate", "metrics.planned": "planned — not yet trained", "forcing.src": "Synthetic scenario",
      "view.3d": "3D digital twin", "view.2d": "2D operations map",
      "cam.overview": "Overview", "cam.delta": "Lowlands", "cam.dams": "Cascade", "cam.hoian": "Hoi An",
      "hint.orbit": "Drag to orbit · scroll to zoom · right-drag to pan", "hint.pan2d": "Drag to pan · scroll to zoom · click gauges/dams",
      "explain.mapHelp": "Use the arrow keys to move the inspection cursor, Enter to select, and Escape to close.",
      "explain.eyebrow": "Normalized physical state", "explain.title": "Explain this state", "explain.close": "Close explanation",
      "explain.quantities": "Quantities", "explain.sources": "Sources and provenance", "explain.confidence": "Uncertainty and confidence",
      "explain.assumptions": "Assumptions", "explain.limitations": "Limitations", "explain.docs": "Read the scientific architecture",
      "explain.degradation": "Degradation evidence", "explain.missingQuantity": "Missing quantity", "explain.missingDependency": "Missing dependency",
      "explain.lastValid": "Last valid time", "explain.confidenceEffect": "Confidence effect", "explain.permittedUse": "Permitted use",
      "explain.status": "Status", "explain.valid": "Valid time", "explain.issue": "Issue time", "explain.notComputed": "not computed",
      "explain.age": "Data age", "explain.quality": "Quality", "explain.flags": "Quality flags", "explain.reason": "Reason",
      "explain.grade": "Confidence grade", "explain.uncertaintyDetail": "Uncertainty", "explain.unavailable": "unavailable",
      "explain.methodGateway": "Explain this state", "explain.selection.point": "Grid cell", "explain.selection.feature": "Feature",
      "explain.label.gauge": "Explain gauge", "explain.label.reservoir": "Explain reservoir",
      "badge.flooded": "Flooded area", "badge.people": "People exposed",
      "fallback.webgl": "WebGL/Three.js unavailable — showing the full-simulation 2D map instead.",
      "tl.observed": "observed", "tl.now": "NOW", "tl.forecast": "ensemble forecast",
      "panel.gauge": "River gauge · probabilistic forecast",
      "gauge.stage": "Stage", "gauge.trend": "3h trend", "gauge.alert": "Alert",
      "chart.obs": "Observed", "chart.median": "Median",
      "panel.reservoir": "Reservoir cascade · Decision 1865/QD-TTg",
      "mpc.title": "Pre-release proposal (MPC · inside legal envelope)",
      "mpc.approve": "Approve", "mpc.details": "Decision package", "mpc.reject": "Reject",
      "mpc.note": "No gate moves on the LLM's word — the duty operator approves every release.",
      "mpc.approved": "APPROVED", "mpc.applied": "Pre-releasing per approved order",
      "panel.traffic": "Continuously updated simulated traffic",
      "tr.open": "Network open", "tr.closed": "Closed links", "tr.reroute": "Rerouted", "tr.eta": "ETA DN→Hoi An",
      "tr.veh": "veh", "tr.blocked": "jam",
      "panel.llm": "Bounded LLM layer · RAG", "llm.grounded": "100% cited",
      "llm.placeholder": "Generate a brief to summarise the situation — every number comes from the solver/optimizer, every clause carries a citation.",
      "llm.generate": "Generate situation brief", "llm.citizen": "Hoi An citizen Q&A",
      "panel.log": "Event log",
      "panel.zones": "Monitored areas", "kpi.zones": "Areas at risk/critical",
      "layer.zones": "Area rings", "layer.bldg": "Buildings", "layer.impact": "Human impact",
      "impact.homes": "Flooded homes",
      "legend.impact": "Human impact", "legend.heat": "Pop × depth heatmap", "legend.h15": "Homes ≥15 cm", "legend.h50": "Homes ≥50 cm",
      "zone.depth": "Max depth", "zone.mean": "Mean depth", "zone.exposed": "Exposed", "zone.access": "EOC access",
      "zone.accessOk": "open", "zone.accessCut": "CUT OFF", "zone.pois": "Critical infrastructure", "zone.actions": "Recommended actions",
      "zone.flyto": "Fly to", "zone.history": "Flood history (T−24h→now)", "zone.gauge": "Nearest gauge",
      "zone.st0": "Safe", "zone.st1": "Watch", "zone.st2": "At risk", "zone.st3": "CRITICAL",
      "zone.toRed": "escalated to CRITICAL", "zone.toOrange": "escalated to at-risk", "zone.improved": "downgraded — improving",
      "zone.ok": "OK", "zone.flooded": "flooded", "modal.zone": "Area detail",
      "foot.mode": "Synthetic demo data illustrating the method — not for real operations", "foot.docs": "Technical documentation", "hint.mobile": "You are on a small screen. The 2D operations map is prioritised; rotate the device or open on a computer to see the reservoir, forecast and zone panels.",
      "alert.bd": "AL", "alert.over": "Above AL3",
      "phase.calm": "Stable", "phase.watch": "Watch", "phase.rise": "Rising", "phase.peak": "Flood peak", "phase.recede": "Receding",
      "unit.people": "people", "unit.min": "min",
      "res.inflow": "in", "res.outflow": "out", "res.ceil": "pre-flood ceiling", "res.gate": "gates", "res.preRelease": "pre-release",
      "modal.decision": "Decision package · MPC pre-release", "modal.brief": "Situation brief (bounded LLM)", "modal.citizen": "Citizen Q&A — Hoi An",
      "dp.proposed": "Proposed release", "dp.envelope": "Ensemble inflow envelope", "dp.legal": "Governing clause", "dp.residual": "Residual risk", "dp.downstream": "Projected downstream",
      "toast.mpcOn": "MPC optimizer armed — pre-release proposal awaiting approval.",
      "toast.approved": "Pre-release approved — downstream forecast updated.",
      "toast.rejected": "Proposal rejected. Keeping rule-curve operation.",
      "toast.scenario": "Scenario loaded", "toast.reroute": "Traffic automatically rerouted around flooded links",
      "tour.btn": "Demo tour",
      "tour.s1": "🎬 Tour — Oct 2020 flood: watch the rise from upstream", "tour.s2": "Riverside lowlands flood first — vehicles start rerouting",
      "tour.s3": "RULE-CURVE peak: Ái Nghĩa exceeds AL3, multiple roads closed", "tour.s4": "FloodTwin MPC sees the peak coming — pre-release proposed, awaiting approval",
      "tour.s5": "Operator APPROVES — reservoirs draw down to receive the flood", "tour.s6": "Same peak under MPC: downstream stage clearly lower — compare both curves",
      "tour.end": "🎬 Tour finished — explore freely", "tour.cancel": "Tour stopped",
      "report.btn": "Export report", "report.title": "FLOOD SITUATION REPORT — VU GIA – THU BON BASIN",
      "report.at": "As of", "report.gauges": "River gauges", "report.res": "Reservoirs", "report.zones": "Priority areas", "report.traffic": "Traffic",
      "report.stage": "Stage (m)", "report.alert": "Alert", "report.level": "Level (m)", "report.ceil": "Pre-flood ceiling", "report.io": "In / Out (m³/s)",
      "report.depth": "Max depth (m)", "report.exposed": "Exposed", "report.access": "EOC access", "report.brief": "Situation summary",
      "modal.method": "Methods — what is real vs synthetic",
      "rec.btn": "Decision record", "modal.record": "Decision record · ledger",
      "rec.none": "No decision recorded yet. Approve or reject a proposal and the record is sealed at the moment you click.",
      "rec.print": "Print · export PDF", "rec.json": "Download JSON", "rec.apxOpt": "Include appendix",
      "rec.superseded": "Context changed — an open decision was recorded as superseded",
      "rec.title": "INTER-RESERVOIR OPERATING DECISION RECORD",
      "rec.wm": "DEMO · UNSIGNED",
      "rec.banner": "Produced by a public demonstration running on synthetic data. This is not a record of any real operation, it carries no signature, and it establishes no accountability.",
      "rec.what": "What was decided", "rec.when": "When", "rec.expect": "What was expected to happen",
      "rec.clause": "Which clause permitted it", "rec.risk": "What could still go wrong",
      "rec.who": "Who decided", "rec.check": "How to check this again",
      "rec.roleDemo": "role not established, the demo has no accounts",
      "rec.foot": "FloodTwin · SkyLabs — demo record, unsigned. The hash is recomputable without contacting us.",
      "rec.apx": "DECISION RECORD APPENDIX", "rec.apxSeq": "Decision sequence",
      "rec.apxGauge": "Gauges at the moment of sealing", "rec.apxRes": "Reservoirs at the moment of sealing",
      "rec.apxForcing": "Forcing and scenario", "rec.apxProv": "Data provenance",
      "rec.out.approved": "APPROVED", "rec.out.rejected": "REJECTED", "rec.out.superseded": "SUPERSEDED",
      "rec.sealed": "Decision record sealed",
      "rec.apxBand": "Ensemble envelope at the peak",
      "rec.bandSrc": "Ensemble quantiles of the in-browser routing, read where the median peaks",
      "rec.clk.client_clock_unsynchronised": "the visitor's own machine clock, unsynchronised",
      "rec.src.terrain_real": "Real terrain (AWS Terrain Tiles)",
      "rec.src.legal_real": "Real legal text (Decision 1865/QĐ-TTg)",
      "rec.src.forcing_synthetic": "Analytic forcing (synthetic)",
      "rec.src.solver_local": "Shallow-water solver running in this browser",
      "log.start": "VGTB digital twin initialised — 4 reservoirs, 2 key gauges, 288² SWE grid.",
      "ev.bd1": "exceeded alert level 1", "ev.bd2": "exceeded alert level 2", "ev.bd3": "exceeded ALERT LEVEL 3", "ev.below": "dropped below alert level 1",
      "ev.roadClosed": "flooded ≥30 cm — road closed", "ev.roadOpen": "water receded — reopened",
      "ev.gateOpen": "increased spillway release", "ev.peak": "flood peak passed at", "ev.rainPeak": "basin rainfall peak",
    },
  };

  FT.i18n = {
    t(key) { return (STR[FT.state.lang] && STR[FT.state.lang][key]) || STR.vi[key] || key; },
    apply(root) {
      (root || document).querySelectorAll("[data-i18n]").forEach((el) => { el.textContent = FT.i18n.t(el.dataset.i18n); });
      document.documentElement.lang = FT.state.lang;
    },
    setLang(lang) { FT.state.lang = lang; FT.i18n.apply(); FT.bus.emit("lang", lang); },
  };

  /* ---------- utils ---------- */
  FT.util = {
    clamp: (v, a, b) => (v < a ? a : v > b ? b : v),
    lerp: (a, b, t) => a + (b - a) * t,
    smoothstep(a, b, t) { const x = FT.util.clamp((t - a) / (b - a), 0, 1); return x * x * (3 - 2 * x); },
    /* standard-normal CDF Φ(z), Abramowitz–Stegun 7.1.26. Used to read a probability
       off the same Gaussian the ensemble band is drawn from, so P(below a level) and
       the P05–P95 envelope come from one estimator (see hydro.js buildProposal, R-33). */
    normCdf(z) {
      // Φ(z) = ½(1 + erf(z/√2)); erf via A&S 7.1.26 (|error| < 1.5e-7)
      const erf = (x) => { const t = 1 / (1 + 0.3275911 * Math.abs(x)); const y = 1 - (((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x); return x >= 0 ? y : -y; };
      return 0.5 * (1 + erf(z / Math.SQRT2));
    },
    fmt(v, d = 1) { return Number(v).toLocaleString(FT.state.lang === "vi" ? "vi-VN" : "en-US", { maximumFractionDigits: d, minimumFractionDigits: d }); },
    fmtInt(v) { return Math.round(v).toLocaleString(FT.state.lang === "vi" ? "vi-VN" : "en-US"); },
    /* sim clock: t hours relative to scenario "now" anchor */
    clock(tH) {
      const anchor = FT.data.SCENARIOS[FT.state.scenario].anchor; // {y,m,d,h}
      const ms = Date.UTC(anchor.y, anchor.m - 1, anchor.d, anchor.h) + tH * 3600e3;
      const dt = new Date(ms);
      const pad = (n) => String(n).padStart(2, "0");
      return { hm: `${pad(dt.getUTCHours())}:${pad(dt.getUTCMinutes())}`, dm: `${pad(dt.getUTCDate())}/${pad(dt.getUTCMonth() + 1)}`, dt };
    },
    rel(tH) { const s = tH < 0 ? "−" : "+"; const a = Math.abs(tH); const h = Math.floor(a); const m = Math.floor((a - h) * 60); return `T${s}${h}h${m ? String(m).padStart(2, "0") : ""}`; },
    /* deterministic pseudo-random */
    mulberry(seed) { let a = seed >>> 0; return function () { a |= 0; a = (a + 0x6d2b79f5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; },
    /* depth (m) → rgba color stops shared by 2D & 3D */
    /* discrete depth bands — flood "density" classes readable at a glance */
    depthColor(d, out) {
      out = out || [0, 0, 0, 0];
      if (d <= 0.02) { out[3] = 0; return out; }
      let r, g, b, a;
      if (d < 0.15) { r = 138; g = 208; b = 238; a = 0.38; }        // lấp xấp
      else if (d < 0.5) { r = 86; g = 168; b = 228; a = 0.58; }     // nông
      else if (d < 1.0) { r = 42; g = 112; b = 206; a = 0.74; }     // trung bình
      else if (d < 2.0) { r = 20; g = 62; b = 162; a = 0.86; }      // sâu
      else { r = 34; g = 26; b = 122; a = 0.93; }                   // rất sâu
      out[0] = r; out[1] = g; out[2] = b; out[3] = a;
      return out;
    },
    roadColor(depth) {
      if (depth >= 0.30) return getCSS("--road-closed");
      if (depth >= 0.15) return getCSS("--road-risk");
      if (depth >= 0.05) return getCSS("--road-caution");
      return getCSS("--road-open");
    },
    /* hazard thresholds — docs/00-foundations/09-typical-values.md §6 */
    CLOSE_DEPTH: 0.30,                       // vehicles stall/float → road closed
    RISK_DEPTH: 0.15,                        // hazardous, passable with care
    roadClass(depth) { return depth >= 0.30 ? 3 : depth >= 0.15 ? 2 : depth >= 0.05 ? 1 : 0; },
    /* Graded depth-exposure function — docs/01-domain-model/04-exposure-and-impact-model.md §3.1.
       Exposure is population × this fraction, NOT a binary "deep enough" count: a shallow
       flood in a market exposes people the old `depth > 0.45` test dropped. The bands are
       the doc's, and this is the single source of truth for world.floodStats and zones. */
    exposureFraction(depth) {
      return depth < 0.15 ? 0
        : depth < 0.30 ? 0.25          // disrupted
        : depth < 0.50 ? 0.60          // affected
        : 1.00;                        // directly affected
    },
    alertColor(level) { return getCSS(`--al-${FT.util.clamp(level, 0, 3)}`); },
  };

  let cssCache = {};
  function getCSS(name) {
    if (!cssCache[name]) cssCache[name] = getComputedStyle(document.documentElement).getPropertyValue(name).trim() || "#888";
    return cssCache[name];
  }
  FT.util.css = getCSS;

  /* ---------- shared toast/log helpers (ui.js renders) ---------- */
  FT.notify = (msg, kind) => FT.bus.emit("toast", { msg, kind: kind || "info" });
  FT.log = (msg, kind, tH) => FT.bus.emit("logEvent", { msg, kind: kind || "info", tH: tH === undefined ? FT.state.timeH : tH });

  /* ---------- production safety net: surface runtime errors, throttled ---------- */
  let lastErrT = 0;
  function surfaceError(msg) {
    const now = Date.now();
    if (now - lastErrT < 10000) return;
    lastErrT = now;
    try { FT.notify(`⚠️ ${String(msg).slice(0, 120)}`, "danger"); } catch (_) { /* toasts not ready */ }
  }
  window.addEventListener("error", (ev) => surfaceError(ev.message || ev.error));
  window.addEventListener("unhandledrejection", (ev) => surfaceError(ev.reason && ev.reason.message ? ev.reason.message : ev.reason));
})();
